fix: Correct memory evaluation during Alltest + FMU features corrections

diff --git a/Tutorials/Alltest b/Tutorials/Alltest
--- a/Tutorials/Alltest
+++ b/Tutorials/Alltest
@@ -20,7 +20,7 @@ clear
 
 #------------------------------------------------------------------------------
 
-# Set the maximum number of parallel jobs
+# Set the maximum number of parallel jobs (default 1)
 MAX_JOBS=1
 
 if [ $# -eq 1 ]
@@ -35,7 +35,7 @@ echo -e "Run tutorials using $MAX_JOBS threads\n"
 
 # Select tutorials in the test suite
 tutorials=(
-    # Tutorial name                 Expected maximum memory usage
+    # Tutorial name                 Expected maximum memory usage (Gb)
     "1D_boiling                     0.2"
     "1D_CHF/imposedPower            0.2"
     "1D_CHF/imposedTemperature      0.2"
@@ -50,16 +50,29 @@ tutorials=(
     "2D_externalSourceDiffusion     0.2"
     "2D_FFTF                        0.3"
     "2D_fullCoupling                0.2"
-    "2D_KNS37-L22                   0.2"
+    "2D_KNS37-L22                   0.3"
     "2D_MSFR                        0.3"
-    "2D_onePhaseAndPointKineticsCoupling    0.2"
+    "2D_onePhaseAndPointKineticsCoupling 0.2"
     "2D_onePhaseAndSubcriticalPointKineticsCoupling 0.2"
     "2D_voidMotionNoPhaseChange     0.2"
     "3D_gFHR                        1.5"
     "3D_NTPfuelAssembly             0.2"
-    "3D_SmallESFR                   0.3"
+    "3D_SmallESFR                   1.0"
     "Godiva_SN                      1.5"
 )
+
+# Add FMU tutorials only if GeN-Foam has been built with FMU4FOAM
+if [ ! -z $LIB_ECI4FOAM ]
+then
+    echo "GeN-Foam has been built with FMI module"
+    echo "Testing tutorials using FMUs"
+
+    tutorials+=(
+        "FMU/powerTemperatureMomentumControl 0.2"
+        "FMU/2D_onePhaseAndPointKineticsCouplingExternalReacivityFMI/comparisonFMU 0.3"
+        "FMU/2D_onePhaseAndPointKineticsCouplingExternalReacivityFMI/PIDcontrol 0.3"
+    )
+fi
 
 #------------------------------------------------------------------------------
 
@@ -101,43 +114,127 @@ done
 
 #------------------------------------------------------------------------------
 
+getUniqueList() {
+    local original_array=("$@")  # Accept the array as arguments
+    local unique_array=()        # Declare an empty array to hold unique elements
+
+
+    # Iterate through the original array
+    for element in "${original_array[@]}"; do
+        # Check if the element is already in the unique_array
+        if [[ ! " ${unique_array[@]} " =~ " ${element} " ]]; then
+            # If not, add it to the unique_array
+            unique_array+=($element)
+        fi
+    done
+
+    echo "${unique_array[@]}"
+}
+
+# Function to convert seconds to hh:mm:ss format
+secondsTo_hhmmss() {
+    local seconds=$1
+    local hours=$((seconds / 3600))
+    local minutes=$(( (seconds % 3600) / 60 ))
+    local seconds=$((seconds % 60))
+    
+    printf "%02d:%02d:%02d\n" $hours $minutes $seconds
+}
+
+getMemoryUsage() {
+    local pid=$1
+    local total=0
+
+    for child_pid in $(pgrep -P $pid)
+    do
+        rss=$(ps -o rss= -p $child_pid)
+        if [ $? -eq 0 ]
+        then
+            cmd=$(ps -o cmd= -p $child_pid)
+            nCore=1
+            if [[ $(echo "$cmd" | grep -c "mpirun -np") -eq 1 ]]
+            then
+                nCore=$(echo "$cmd" | cut  -d' ' -f3)
+            fi
+            # echo $child_pid $cmd $rss $nCore $(($rss / $nCore))
+            total=$(($total + $rss + $(($(getMemoryUsage $child_pid) / $nCore))))
+            # getMemoryUsage $child_pid
+        fi
+    done
+
+    echo $total
+}
+
+
+# Run the tutorial with time/memory consumption info
 executeAlltest() {
     tutorialName=$1
     expectedMemory=$2
 
     echo -e "Running tutorial $tutorialName ...\n"
 
-    # Run the tutorial with time/memory consumption info
+    # Change folder and clean
     cd $tutorialName
-    # ./Allclean
-    # /usr/bin/time -v -o log.time ./Alltest
-    result=0 # $? # Get the exit code from Alltest (0: success; 1: failed)
-    cd $rootPath
+    ./Allclean
+    
+    # Start time measurement
+    startTime=$(date +%s)
 
-    # Extract memory and time usage
-    memoryUsage=$(grep "Maximum resident set size (kbytes):" $tutorialName/log.time | cut -f6 -d' ')
-    memoryUsageGb=$(echo "scale=3; $memoryUsage / (1024 * 1024)" | bc)
-    timeUsage=$(grep "Elapsed (wall clock) time (h:mm:ss or m:ss):" $tutorialName/log.time | cut -f8 -d' ')
+    # Start the command in the background and recover process ID
+    ./Alltest &
+    local pid=$!
 
-    # Check memory overflow
+    # Monitor the peak memory usage until the command finishes
+    maxMemoryUsage=0
+    while ps -p $pid > /dev/null
+    do
+        tempMaxMemoryUsage=$(getMemoryUsage $pid)
+
+        if [[ $tempMaxMemoryUsage -gt $maxMemoryUsage ]]
+        then
+            maxMemoryUsage=$tempMaxMemoryUsage
+        fi
+
+        sleep 1
+    done
+
+    # Wait for ./Alltest to finish and capture its exit status (0: success; 1: failed)
+    wait $pid
+    local exitStatus=$?
+
+    # End time measurement
+    endTime=$(date +%s)
+    timeUsage=$(secondsTo_hhmmss $(($endTime - $startTime)))
+    echo "$tutorialName time usage: $timeUsage"
+    
+    # Convert to memory usage from kb to Gb
+    maxMemoryUsageGb=$(echo "scale=3; $maxMemoryUsage / (1024 * 1024)" | bc)
+
+    # Check memory overflow (exceeds expected value)
     isMemoryOverflow=0
-    memoryOverflowText=Passed
-    if (( $(echo "$memoryUsageGb > $expectedMemory" | bc -l) ))
+    memoryOverflowText="Passed"
+    if (( $(echo "$maxMemoryUsageGb > $expectedMemory" | bc -l) ))
     then
         isMemoryOverflow=1
         memoryOverflowText="**Failed**"
+        echo "$tutorialName Memory overflow ($maxMemoryUsageGb > $expectedMemory)"
+    else
+        echo "$tutorialName Memory OK ($maxMemoryUsageGb < $expectedMemory)"
     fi
 
 
+    # Return to root folder
+    cd $rootPath
+
     # Update successful tutotial run in summary table
-    if [ $result -eq 0 ] && [ $isMemoryOverflow -eq 0 ]
+    if [ $exitStatus -eq 0 ] && [ $isMemoryOverflow -eq 0 ]
     then
-        sed -i "s,| $tutorialName | \[\!\[regressionTest\]($badgePending)\]() |,| $tutorialName | \[\!\[Alltest\]($badgeSuccess)\]() | $timeUsage | $memoryUsageGb < $expectedMemory |," $resFile
+        sed -i "s,| $tutorialName | \[\!\[regressionTest\]($badgePending)\]() |,| $tutorialName | \[\!\[Alltest\]($badgeSuccess)\]() | $timeUsage | $maxMemoryUsageGb < $expectedMemory |," $resFile
     elif [ $isMemoryOverflow -eq 1 ]
     then
-        sed -i "s,| $tutorialName | \[\!\[regressionTest\]($badgePending)\]() |,| $tutorialName | \[\!\[Memory overflow\]($badgeMemoryOverflow)\]() | $timeUsage | $memoryUsageGb > $expectedMemory |," $resFile
+        sed -i "s,| $tutorialName | \[\!\[regressionTest\]($badgePending)\]() |,| $tutorialName | \[\!\[Memory overflow\]($badgeMemoryOverflow)\]() | $timeUsage | $maxMemoryUsageGb > $expectedMemory |," $resFile
     else
-        sed -i "s,| $tutorialName | \[\!\[regressionTest\]($badgePending)\]() |,| $tutorialName | \[\!\[Alltest\]($badgeFailed)\]() | $timeUsage | $memoryUsageGb < $expectedMemory |," $resFile
+        sed -i "s,| $tutorialName | \[\!\[regressionTest\]($badgePending)\]() |,| $tutorialName | \[\!\[Alltest\]($badgeFailed)\]() | $timeUsage | $maxMemoryUsageGb < $expectedMemory |," $resFile
     fi
 
 
@@ -145,21 +242,21 @@ executeAlltest() {
     sed -i "s|## $tutorialName|## $tutorialName\n\n\
 outputAlltest$tutorialName\n\n\
 Time = $timeUsage\n\n\
-Memory = $memoryUsageGb Gb ($memoryOverflowText, expected: $expectedMemory Gb)|" $resFile
+Memory = $maxMemoryUsageGb Gb ($memoryOverflowText, expected: $expectedMemory Gb)|" $resFile
 
     # Replace / to \/
-    escaped_pattern=$(sed 's/[\/&]/\\&/g' <<< "outputAlltest$tutorialName")
+    escapedPattern=$(sed 's/[\/&]/\\&/g' <<< "outputAlltest$tutorialName")
 
     # Write output file test.out into the main MD file
-    sed -i "/$escaped_pattern/r $tutorialName/test.out" $resFile
+    sed -i "/$escapedPattern/r $tutorialName/test.out" $resFile
     # Remove delimiter
-    sed -i "/$escaped_pattern/d" $resFile
+    sed -i "/$escapedPattern/d" $resFile
 }
 
 #------------------------------------------------------------------------------
 
 # Counter for the number of background jobs
-job_count=0
+jobCount=0
 
 # Run all tutorials and check for clean finish
 for tutorial_i in "${tutorials[@]}"
@@ -174,16 +271,15 @@ do
     echo -e "\n--------------------------------------------------------------------------------\n" >> $resFile
     echo -e "## $tutorialName" >> $resFile
 
-
-    # Execute alltest and extract the results in background
+    # Execute Alltest (time and memory usage monitoring) and extract the results
+    # in background
     executeAlltest $tutorialName $expectedMemory &
 
-
     # Decrement or wait job
-    ((job_count++))
-    if (( $job_count >= $MAX_JOBS )); then
+    ((jobCount++))
+    if (( $jobCount >= $MAX_JOBS )); then
         wait -n  # Wait for any job to finish
-        ((job_count--))
+        ((jobCount--))
     fi
 done
 
