Minor modifications to some Infos in some neutronics header files. Added a gnuplot script in Tools/residualsPlot/ to plot all avaialble residuals from a log file. Said script has been added to all tutorials and its usage scripted to run (and close) automatically, if gnuplot is available (no problems otherwise), with the Allrun scripts

diff --git a/Tutorials/2D_FFTF/Allrun b/Tutorials/2D_FFTF/Allrun
--- a/Tutorials/2D_FFTF/Allrun
+++ b/Tutorials/2D_FFTF/Allrun
@@ -75,9 +75,21 @@ do
         ;;
     esac
 
+    # Start gnuplot if it exist
+    if ! command -v gnuplot &> /dev/null
+    then
+        echo "gnuplot could not be found"
+    else
+        gnuplot -e "log='$caseName/log.$exe'" residuals - &> /dev/null &
+    fi
+
     printf "Running $exe on $caseName\n"
-    
     $exe -case $caseName | tee "$caseName/log.GeN-Foam"
 
+    # Kill gnuplot if it was started
+    if command -v gnuplot &> /dev/null
+    then
+        pkill -x gnuplot
+    fi
 
 done
diff --git a/Tutorials/2D_cavityBoussinesq/Allrun b/Tutorials/2D_cavityBoussinesq/Allrun
--- a/Tutorials/2D_cavityBoussinesq/Allrun
+++ b/Tutorials/2D_cavityBoussinesq/Allrun
@@ -1,5 +1,19 @@
 #!/bin/sh
 exe="GeN-Foam"
+
+# Start gnuplot if it exist
+if ! command -v gnuplot &> /dev/null
+then
+    echo "gnuplot could not be found"
+else
+    gnuplot residuals - &> /dev/null &
+fi
+
+# Run GeN-Foam
 $exe | tee log.GeN-Foam
 
-
+# Kill gnuplot if it was started
+if command -v gnuplot &> /dev/null
+then
+    pkill -x gnuplot
+fi
diff --git a/Tutorials/2D_onePhaseAndPointKineticsCoupling/Allrun b/Tutorials/2D_onePhaseAndPointKineticsCoupling/Allrun
--- a/Tutorials/2D_onePhaseAndPointKineticsCoupling/Allrun
+++ b/Tutorials/2D_onePhaseAndPointKineticsCoupling/Allrun
@@ -64,24 +64,32 @@ do
     case "$caseName" in
     "steadyState")
         setSteadyState rootCase $caseName
-        printf "Running $exe on $caseName\n"
-        cd $caseName
-        $exe | tee "log.GeN-Foam"
-        cd ..
         ;;
     "transientNoDriveline")
         setTransientNoDriveline steadyState $caseName
-        cd $caseName
-        $exe | tee "log.GeN-Foam"
-        cd ..
+
         ;;
     "transientWithDriveline")
         setTransientWithDriveline steadyState $caseName
-        cd $caseName
-        $exe | tee "log.GeN-Foam"
-        cd ..
         ;;
     esac
+
+    # Start gnuplot if it exist
+    if ! command -v gnuplot &> /dev/null
+    then
+        echo "gnuplot could not be found"
+    else
+        gnuplot -e "log='$caseName/log.$exe'" residuals - &> /dev/null &
+    fi
+
+    printf "Running $exe on $caseName\n"
+    $exe -case $caseName 2>&1 | tee "$caseName/log.$exe"
+
+    # Kill gnuplot if it was started
+    if command -v gnuplot &> /dev/null
+    then
+        pkill -x gnuplot
+    fi
 
     printf "Running $exe on $caseName\n"
 done
diff --git a/Tutorials/3D_SmallESFR/Allrun_parallel b/Tutorials/3D_SmallESFR/Allrun_parallel
--- a/Tutorials/3D_SmallESFR/Allrun_parallel
+++ b/Tutorials/3D_SmallESFR/Allrun_parallel
@@ -44,28 +44,34 @@ do
     "steadyState")
         runCloneCase $caseName rootCase
         printf "Steady state case is prepared!\n"
-    	printf "Running $exe on $caseName\n"
-    	decomposePar -case $caseName -region thermoMechanicalRegion
-    	decomposePar -case $caseName -region neutroRegion
-    	decomposePar -case $caseName -region fluidRegion
-    	cd $caseName
-    	runParallel $exe
-    	cd ../
-
+        printf "Running $exe on $caseName\n"
+        decomposePar -case $caseName -region thermoMechanicalRegion
+        decomposePar -case $caseName -region neutroRegion
+        decomposePar -case $caseName -region fluidRegion
         ;;
     "transient")
         printf "Transient case entered...\n"
         setTransient $caseName steadyState
-    	printf "Running $exe on $caseName\n"
-    	cd $caseName
-    	runParallel $exe
-    	cd ../
         ;;
     esac
 
-    #( cd $caseName && runApplication `getApplication` )
-    #mpirun -np 4 $exe -parallel -case $caseName 2>&1 | tee "$caseName/log.$exe"
-    #$exe -case $caseName 2>&1 | tee "$caseName/log.$exe"
+    # Start gnuplot if it exist
+    if ! command -v gnuplot &> /dev/null
+    then
+        echo "gnuplot could not be found"
+    else
+        gnuplot -e "log='$caseName/log.$exe'" residuals - &> /dev/null &
+    fi
+
+    printf "Running $exe on $caseName\n"
+    mpirun -np 4 $exe -parallel -case $caseName | tee "$caseName/log.GeN-Foam"
+
+    # Kill gnuplot if it was started
+    if command -v gnuplot &> /dev/null
+    then
+        pkill -x gnuplot
+    fi
+
 done
 
 #------------------------------------------------------------------------------
diff --git a/Tutorials/Godiva_SN/Allrun_parallel b/Tutorials/Godiva_SN/Allrun_parallel
--- a/Tutorials/Godiva_SN/Allrun_parallel
+++ b/Tutorials/Godiva_SN/Allrun_parallel
@@ -1,7 +1,21 @@
 #!/bin/sh
 exe="GeN-Foam"
+
+# Start gnuplot if it exist
+if ! command -v gnuplot &> /dev/null
+then
+    echo "gnuplot could not be found"
+else
+    gnuplot residuals - &> /dev/null &
+fi
+
 decomposePar -region thermoMechanicalRegion
 decomposePar -region fluidRegion
 decomposePar -region neutroRegion
 mpirun -np 4 $exe -parallel | tee log.GeN-Foam
 
+# Kill gnuplot if it was started
+if command -v gnuplot &> /dev/null
+then
+    pkill -x gnuplot
+fi
